# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 660)
        self.tabWidget = QtWidgets.QTabWidget(parent=MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 760, 560))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")

        self.ProgressTab = QtWidgets.QWidget()
        self.ProgressTab.setObjectName("ProgressTab")

        self.SubjectLabel = QtWidgets.QLabel(parent=self.ProgressTab)
        self.SubjectLabel.setGeometry(QtCore.QRect(30, 30, 80, 30))
        self.SubjectLabel.setObjectName("SubjectLabel")

        self.SubjectLineEdit = QtWidgets.QLineEdit(parent=self.ProgressTab)
        self.SubjectLineEdit.setGeometry(QtCore.QRect(160, 30, 250, 30))
        self.SubjectLineEdit.setObjectName("SubjectLineEdit")

        self.SubjectErrorLabel = QtWidgets.QLabel(parent=self.ProgressTab)
        self.SubjectErrorLabel.setGeometry(QtCore.QRect(420, 30, 250, 30))
        self.SubjectErrorLabel.setStyleSheet("color: red;")
        self.SubjectErrorLabel.setObjectName("SubjectErrorLabel")

        self.DateLabel = QtWidgets.QLabel(parent=self.ProgressTab)
        self.DateLabel.setGeometry(QtCore.QRect(30, 80, 80, 30))
        self.DateLabel.setObjectName("DateLabel")

        self.DateEdit = QtWidgets.QDateEdit(parent=self.ProgressTab)
        self.DateEdit.setGeometry(QtCore.QRect(160, 80, 150, 30))
        self.DateEdit.setMinimumDate(QtCore.QDate(2023, 1, 1))
        self.DateEdit.setCalendarPopup(True)
        self.DateEdit.setObjectName("DateEdit")

        self.DurationLabel = QtWidgets.QLabel(parent=self.ProgressTab)
        self.DurationLabel.setGeometry(QtCore.QRect(30, 130, 120, 30))
        self.DurationLabel.setObjectName("DurationLabel")

        self.SpinBox = QtWidgets.QSpinBox(parent=self.ProgressTab)
        self.SpinBox.setGeometry(QtCore.QRect(160, 130, 80, 30))
        self.SpinBox.setMinimum(1)
        self.SpinBox.setMaximum(1000)
        self.SpinBox.setObjectName("SpinBox")

        self.DurationErrorLabel = QtWidgets.QLabel(parent=self.ProgressTab)
        self.DurationErrorLabel.setGeometry(QtCore.QRect(250, 130, 250, 30))
        self.DurationErrorLabel.setStyleSheet("color: red;")
        self.DurationErrorLabel.setObjectName("DurationErrorLabel")

        self.NotesLabel = QtWidgets.QLabel(parent=self.ProgressTab)
        self.NotesLabel.setGeometry(QtCore.QRect(30, 180, 80, 30))
        self.NotesLabel.setObjectName("NotesLabel")

        self.NotesTextEdit = QtWidgets.QTextEdit(parent=self.ProgressTab)
        self.NotesTextEdit.setGeometry(QtCore.QRect(160, 180, 480, 100))
        self.NotesTextEdit.setObjectName("NotesTextEdit")

        self.AddSessionPushButton = QtWidgets.QPushButton(parent=self.ProgressTab)
        self.AddSessionPushButton.setGeometry(QtCore.QRect(160, 300, 120, 40))
        self.AddSessionPushButton.setObjectName("AddSessionPushButton")

        self.ClearPushButton = QtWidgets.QPushButton(parent=self.ProgressTab)
        self.ClearPushButton.setGeometry(QtCore.QRect(320, 300, 120, 40))
        self.ClearPushButton.setObjectName("ClearPushButton")

        self.tabWidget.addTab(self.ProgressTab, "")

        self.CalenderTab = QtWidgets.QWidget()
        self.CalenderTab.setObjectName("CalenderTab")
        self.CalendarWidget = QtWidgets.QCalendarWidget(parent=self.CalenderTab)
        self.CalendarWidget.setGeometry(QtCore.QRect(40, 40, 680, 480))
        self.CalendarWidget.setObjectName("CalendarWidget")
        self.SessionDetailsTextEdit = QtWidgets.QTextEdit(parent=self.CalenderTab)
        self.SessionDetailsTextEdit.setGeometry(QtCore.QRect(40, 530, 680, 50))
        self.SessionDetailsTextEdit.setObjectName("SessionDetailsTextEdit")
        self.tabWidget.addTab(self.CalenderTab, "")

        self.ProgressTab1 = QtWidgets.QWidget()
        self.ProgressTab1.setObjectName("ProgressTab1")
        self.SummaryLabel = QtWidgets.QLabel(parent=self.ProgressTab1)
        self.SummaryLabel.setGeometry(QtCore.QRect(30, 30, 160, 30))
        self.SummaryLabel.setObjectName("SummaryLabel")
        self.TableWidget = QtWidgets.QTableWidget(parent=self.ProgressTab1)
        self.TableWidget.setGeometry(QtCore.QRect(30, 80, 700, 460))
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.tabWidget.addTab(self.ProgressTab1, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Study Session Planner"))
        self.SubjectLabel.setText(_translate("MainWindow", "Subject"))
        self.DateLabel.setText(_translate("MainWindow", "Date"))
        self.DurationLabel.setText(_translate("MainWindow", "Duration(min)"))
        self.NotesLabel.setText(_translate("MainWindow", "Notes"))
        self.AddSessionPushButton.setText(_translate("MainWindow", "Add Session"))
        self.ClearPushButton.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ProgressTab), _translate("MainWindow", "Planner"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CalenderTab), _translate("MainWindow", "Calender"))
        self.SummaryLabel.setText(_translate("MainWindow", "Session Summary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ProgressTab1), _translate("MainWindow", "Progress"))
